pylint: Provide ignore paths for Pylint 2.14.4+
New pylint 2.14.4 includes fix for
https://github.com/PyCQA/pylint/issues/6964, this results in our pylint
configuration for `ignore-paths` is no longer valid (`./.tox` => `.tox`)
and pylint fails on checking not related projects from `.tox` directory:

> ERROR: InvocationError for command /home/runner/work/tox-no-deps/tox-no-deps/.tox/pylint/bin/python -m pylint -v --rcfile=/home/runner/work/tox-no-deps/tox-no-deps/pyproject.toml . (exited with code 30)

Fixes: https://github.com/stanislavlevin/tox-no-deps/issues/9
Signed-off-by: Stanislav Levin <slev@altlinux.org>